/* The C declarations, named once, so that every toolchain that builds this
 * suite compiles them.
 *
 * Clause 4.3 requires the two forms of the declarations to declare the same
 * entities, and tools/check-declarations.sh performs that comparison against
 * SURFACE.txt --- which is normative --- with the environment's own headers
 * excluded. That tool needs a compiler driver it can pass -nostdinc to, and one
 * of the three toolchains this suite is built with has no such spelling. So the
 * comparison is performed in one place and the compiling is performed here, in
 * a translation unit the suite carries: a header that fails to compile as C
 * under a toolchain then fails that toolchain's build rather than going
 * unnoticed until a C consumer meets it.
 *
 * No name is referenced in an evaluated context. The suite is composable --- an
 * implementation provides an interface in whole or not at all --- so a file that
 * required all fifty-one definitions would fail to link against a conforming
 * implementation of three interfaces, which is the arrangement the suite exists
 * to accommodate. sizeof is unevaluated, so this file declares a dependency on
 * nothing while still rejecting a name the header fails to declare.
 *
 * Regenerated by tools/check-declarations.sh --write. It is committed rather
 * than generated during the build so that the suite compiles in a checkout that
 * has nothing but a compiler.
 */
#include <openkal.h>

void okc_declarations_c(void);
void okc_declarations_c(void)
{
    (void)sizeof(&kal_abort);
    (void)sizeof(&kal_alloc);
    (void)sizeof(&kal_datagram_close);
    (void)sizeof(&kal_datagram_local);
    (void)sizeof(&kal_datagram_open);
    (void)sizeof(&kal_datagram_props);
    (void)sizeof(&kal_datagram_recv_from);
    (void)sizeof(&kal_datagram_send_to);
    (void)sizeof(&kal_env_arg);
    (void)sizeof(&kal_env_arg_count);
    (void)sizeof(&kal_env_var);
    (void)sizeof(&kal_env_var_at);
    (void)sizeof(&kal_env_var_count);
    (void)sizeof(&kal_exec_alloc);
    (void)sizeof(&kal_exec_free);
    (void)sizeof(&kal_exec_props);
    (void)sizeof(&kal_exec_publish);
    (void)sizeof(&kal_exit);
    (void)sizeof(&kal_free);
    (void)sizeof(&kal_fs_close_dir);
    (void)sizeof(&kal_fs_close_file);
    (void)sizeof(&kal_fs_file_info);
    (void)sizeof(&kal_fs_info);
    (void)sizeof(&kal_fs_list_begin);
    (void)sizeof(&kal_fs_list_next);
    (void)sizeof(&kal_fs_mkdir);
    (void)sizeof(&kal_fs_open);
    (void)sizeof(&kal_fs_open_dir);
    (void)sizeof(&kal_fs_open_file);
    (void)sizeof(&kal_fs_preopen);
    (void)sizeof(&kal_fs_preopen_count);
    (void)sizeof(&kal_fs_props);
    (void)sizeof(&kal_fs_remove);
    (void)sizeof(&kal_fs_rename);
    (void)sizeof(&kal_fs_seek);
    (void)sizeof(&kal_fs_set_modified);
    (void)sizeof(&kal_fs_stream);
    (void)sizeof(&kal_fs_truncate);
    (void)sizeof(&kal_net_accept);
    (void)sizeof(&kal_net_close);
    (void)sizeof(&kal_net_close_listener);
    (void)sizeof(&kal_net_connect);
    (void)sizeof(&kal_net_listen);
    (void)sizeof(&kal_net_listener_local);
    (void)sizeof(&kal_net_local);
    (void)sizeof(&kal_net_peer);
    (void)sizeof(&kal_net_props);
    (void)sizeof(&kal_net_shutdown);
    (void)sizeof(&kal_net_stream);
    (void)sizeof(&kal_process_channel);
    (void)sizeof(&kal_process_channel_close);
    (void)sizeof(&kal_process_close);
    (void)sizeof(&kal_process_props);
    (void)sizeof(&kal_process_spawn);
    (void)sizeof(&kal_process_spawn_with);
    (void)sizeof(&kal_process_terminate);
    (void)sizeof(&kal_process_wait);
    (void)sizeof(&kal_random_fill);
    (void)sizeof(&kal_random_props);
    (void)sizeof(&kal_space_props);
    (void)sizeof(&kal_space_start);
    (void)sizeof(&kal_stderr);
    (void)sizeof(&kal_stdin);
    (void)sizeof(&kal_stdout);
    (void)sizeof(&kal_stream_flush);
    (void)sizeof(&kal_stream_props);
    (void)sizeof(&kal_stream_read);
    (void)sizeof(&kal_stream_write);
    (void)sizeof(&kal_task_current);
    (void)sizeof(&kal_task_join);
    (void)sizeof(&kal_task_props);
    (void)sizeof(&kal_task_start);
    (void)sizeof(&kal_task_wait);
    (void)sizeof(&kal_task_wake);
    (void)sizeof(&kal_task_yield);
    (void)sizeof(&kal_terminal_get_mode);
    (void)sizeof(&kal_terminal_props);
    (void)sizeof(&kal_terminal_set_mode);
    (void)sizeof(&kal_terminal_size);
    (void)sizeof(&kal_time_monotonic);
    (void)sizeof(&kal_time_monotonic_granularity);
    (void)sizeof(&kal_timeout_accept);
    (void)sizeof(&kal_timeout_granularity_ns);
    (void)sizeof(&kal_timeout_read);
    (void)sizeof(&kal_timeout_recv_from);
    (void)sizeof(&kal_timeout_wait_process);
    (void)sizeof(&kal_timeout_write);
    (void)sizeof(&kal_time_props);
    (void)sizeof(&kal_time_sleep);
    (void)sizeof(&kal_time_wall);
}
