#!/usr/bin/env bash
# Generate src/macros.cppm from the headers.
#
# ⚠️⚠️ THIS EXISTS BECAUSE THE SAME DEFECT HAPPENED TWICE. `KAL_LOCK_*' in 0.10
# and `KAL_SPAWN_*' in 0.11 were both added to a header, both used from a module
# consumer, and both failed to compile there --- because a macro DOES NOT CROSS A
# MODULE BOUNDARY, and nothing checked that every macro had a module spelling.
#
# ⇒ So the mapping is generated rather than written. A macro added to a header
# and not to this module is not a thing anyone has to remember: CI regenerates
# and diffs, so forgetting is a red build rather than a consumer's compile error
# two repositories away.
#
# Object-like macros only. A function-like one (`KAL_VERSION_MAKE') is not a
# constant and has no constexpr spelling; those are listed as skipped so that
# "absent" is never silently the same as "not applicable".
set -euo pipefail

cd "$(dirname "$0")/.."
out=src/macros.cppm

names=$(grep -rhoE '^#define +KAL_[A-Z0-9_]+' include/openkal/*.h \
        | awk '{print $2}' | sort -u)
skipped=$(grep -rhoE '^#define +KAL_[A-Z0-9_]+\(' include/openkal/*.h \
        | awk '{print $2}' | sed 's/(.*//' | sort -u)

{
cat <<'HEAD'
// Every KAL_ macro, as a constant a module consumer can name.
//
// ⚠️⚠️ GENERATED BY tools/gen-macros.sh. Do not edit; CI regenerates this file
// and fails on a difference.
//
// A macro does not cross a module boundary. Twice now a capability word has been
// added to a header, used from a module consumer, and failed to compile there ---
// `KAL_LOCK_*' in 0.10 and `KAL_SPAWN_*' in 0.11. The interface modules give the
// well-named subset (`kal::fs::lock::exclusive'); this gives ALL of them under
// the C spelling with a `_M' suffix, so that a name in the header always exists
// here too and the two cannot drift.
module;
HEAD

# Every header, so that a macro cannot be missed by an include list that was not
# updated either --- the same failure one level down.
for h in $(ls include/openkal/*.h | xargs -n1 basename | sort); do
    printf '#include <openkal/%s>\n' "$h"
done

cat <<'MID'
export module openkal.macros;
export import openkal.types;

export namespace kal::macros {
MID

# ⚠️ THE DECLARED NAME CANNOT BE THE MACRO'S NAME: the macro is still defined
# here, so `constexpr kal_uintptr KAL_VERSION_MAJOR = …' expands on the LEFT as
# well and becomes `constexpr kal_uintptr 0u = …'.
#
# ⭐ `_M' RATHER THAN LOWER-CASING. The C spelling is what a reader is looking
# for --- they arrived here because the header said `KAL_SPAWN_OWN_JOB' --- so the
# name is kept and marked. `KAL_SPAWN_OWN_JOB_M' is a different token, so the
# preprocessor leaves it alone, and the suffix says what it is: the module
# spelling of a macro.
for n in $names; do
    case " $skipped " in *" $n "*) continue;; esac
    printf 'inline constexpr kal_uintptr %-34s = (kal_uintptr)(%s);\n' "${n}_M" "$n"
done

echo '}  // namespace kal::macros'
echo
echo '// Function-like, and therefore not constants --- listed so that their absence'
echo '// above is a stated fact rather than a gap:'
for n in $skipped; do echo "//   $n"; done
} > "$out"

echo "wrote $out: $(grep -c '^inline constexpr' "$out") constants, $(echo "$skipped" | wc -w) function-like skipped"
