// Every KAL_ macro, as a constant a module consumer can name.
//
// ⚠️⚠️ GENERATED BY tools/gen-macros.sh. Do not edit; CI regenerates this file
// and fails on a difference.
//
// A macro does not cross a module boundary. Twice now a capability word has been
// added to a header, used from a module consumer, and failed to compile there ---
// `KAL_LOCK_*' in 0.10 and `KAL_SPAWN_*' in 0.11. The interface modules give the
// well-named subset (`kal::fs::lock::exclusive'); this gives ALL of them, one per
// macro, so that a name which exists in the header always exists here
// too and the two cannot drift.
module;
#include <openkal/abort.h>
#include <openkal/datagram.h>
#include <openkal/env.h>
#include <openkal/exec.h>
#include <openkal/fs.h>
#include <openkal/memory.h>
#include <openkal/net.h>
#include <openkal/process.h>
#include <openkal/random.h>
#include <openkal/space.h>
#include <openkal/stream.h>
#include <openkal/task.h>
#include <openkal/terminal.h>
#include <openkal/time.h>
#include <openkal/timeout.h>
#include <openkal/types.h>
#include <openkal/version.h>
export module openkal.macros;
export import openkal.types;

export namespace kal::macros {
inline constexpr kal_uintptr dgram_prop_broadcast         = (kal_uintptr)(KAL_DGRAM_PROP_BROADCAST);
inline constexpr kal_uintptr dgram_prop_ipv6              = (kal_uintptr)(KAL_DGRAM_PROP_IPV6);
inline constexpr kal_uintptr exec_prop_available          = (kal_uintptr)(KAL_EXEC_PROP_AVAILABLE);
inline constexpr kal_uintptr exec_prop_republish          = (kal_uintptr)(KAL_EXEC_PROP_REPUBLISH);
inline constexpr kal_uintptr fs_link_directory            = (kal_uintptr)(KAL_FS_LINK_DIRECTORY);
inline constexpr kal_uintptr fs_no_resolve                = (kal_uintptr)(KAL_FS_NO_RESOLVE);
inline constexpr kal_uintptr fs_prop_atomic_rename        = (kal_uintptr)(KAL_FS_PROP_ATOMIC_RENAME);
inline constexpr kal_uintptr fs_prop_capacity             = (kal_uintptr)(KAL_FS_PROP_CAPACITY);
inline constexpr kal_uintptr fs_prop_case_sensitive       = (kal_uintptr)(KAL_FS_PROP_CASE_SENSITIVE);
inline constexpr kal_uintptr fs_prop_links                = (kal_uintptr)(KAL_FS_PROP_LINKS);
inline constexpr kal_uintptr fs_prop_locks                = (kal_uintptr)(KAL_FS_PROP_LOCKS);
inline constexpr kal_uintptr fs_prop_make_links           = (kal_uintptr)(KAL_FS_PROP_MAKE_LINKS);
inline constexpr kal_uintptr fs_prop_modified_time        = (kal_uintptr)(KAL_FS_PROP_MODIFIED_TIME);
inline constexpr kal_uintptr iface_abort                  = (kal_uintptr)(KAL_IFACE_ABORT);
inline constexpr kal_uintptr iface_datagram               = (kal_uintptr)(KAL_IFACE_DATAGRAM);
inline constexpr kal_uintptr iface_env                    = (kal_uintptr)(KAL_IFACE_ENV);
inline constexpr kal_uintptr iface_exec                   = (kal_uintptr)(KAL_IFACE_EXEC);
inline constexpr kal_uintptr iface_fs                     = (kal_uintptr)(KAL_IFACE_FS);
inline constexpr kal_uintptr iface_memory                 = (kal_uintptr)(KAL_IFACE_MEMORY);
inline constexpr kal_uintptr iface_net                    = (kal_uintptr)(KAL_IFACE_NET);
inline constexpr kal_uintptr iface_process                = (kal_uintptr)(KAL_IFACE_PROCESS);
inline constexpr kal_uintptr iface_random                 = (kal_uintptr)(KAL_IFACE_RANDOM);
inline constexpr kal_uintptr iface_space                  = (kal_uintptr)(KAL_IFACE_SPACE);
inline constexpr kal_uintptr iface_stream                 = (kal_uintptr)(KAL_IFACE_STREAM);
inline constexpr kal_uintptr iface_task                   = (kal_uintptr)(KAL_IFACE_TASK);
inline constexpr kal_uintptr iface_terminal               = (kal_uintptr)(KAL_IFACE_TERMINAL);
inline constexpr kal_uintptr iface_time                   = (kal_uintptr)(KAL_IFACE_TIME);
inline constexpr kal_uintptr iface_timeout                = (kal_uintptr)(KAL_IFACE_TIMEOUT);
inline constexpr kal_uintptr info_all                     = (kal_uintptr)(KAL_INFO_ALL);
inline constexpr kal_uintptr info_identity                = (kal_uintptr)(KAL_INFO_IDENTITY);
inline constexpr kal_uintptr info_kind                    = (kal_uintptr)(KAL_INFO_KIND);
inline constexpr kal_uintptr info_modified                = (kal_uintptr)(KAL_INFO_MODIFIED);
inline constexpr kal_uintptr info_size                    = (kal_uintptr)(KAL_INFO_SIZE);
inline constexpr kal_uintptr info_writable                = (kal_uintptr)(KAL_INFO_WRITABLE);
inline constexpr kal_uintptr lock_exclusive               = (kal_uintptr)(KAL_LOCK_EXCLUSIVE);
inline constexpr kal_uintptr lock_shared                  = (kal_uintptr)(KAL_LOCK_SHARED);
inline constexpr kal_uintptr lock_wait                    = (kal_uintptr)(KAL_LOCK_WAIT);
inline constexpr kal_uintptr net_prop_halfclose           = (kal_uintptr)(KAL_NET_PROP_HALFCLOSE);
inline constexpr kal_uintptr net_prop_ipv6                = (kal_uintptr)(KAL_NET_PROP_IPV6);
inline constexpr kal_uintptr open_append                  = (kal_uintptr)(KAL_OPEN_APPEND);
inline constexpr kal_uintptr open_create                  = (kal_uintptr)(KAL_OPEN_CREATE);
inline constexpr kal_uintptr open_exclusive               = (kal_uintptr)(KAL_OPEN_EXCLUSIVE);
inline constexpr kal_uintptr open_read                    = (kal_uintptr)(KAL_OPEN_READ);
inline constexpr kal_uintptr open_truncate                = (kal_uintptr)(KAL_OPEN_TRUNCATE);
inline constexpr kal_uintptr open_write                   = (kal_uintptr)(KAL_OPEN_WRITE);
inline constexpr kal_uintptr process_prop_bound_lifetime  = (kal_uintptr)(KAL_PROCESS_PROP_BOUND_LIFETIME);
inline constexpr kal_uintptr process_prop_channel         = (kal_uintptr)(KAL_PROCESS_PROP_CHANNEL);
inline constexpr kal_uintptr process_prop_exit_status     = (kal_uintptr)(KAL_PROCESS_PROP_EXIT_STATUS);
inline constexpr kal_uintptr process_prop_grant_dir       = (kal_uintptr)(KAL_PROCESS_PROP_GRANT_DIR);
inline constexpr kal_uintptr process_prop_own_job         = (kal_uintptr)(KAL_PROCESS_PROP_OWN_JOB);
inline constexpr kal_uintptr process_prop_stream_passing  = (kal_uintptr)(KAL_PROCESS_PROP_STREAM_PASSING);
inline constexpr kal_uintptr process_prop_terminate       = (kal_uintptr)(KAL_PROCESS_PROP_TERMINATE);
inline constexpr kal_uintptr random_prop_blocking         = (kal_uintptr)(KAL_RANDOM_PROP_BLOCKING);
inline constexpr kal_uintptr random_prop_hardware         = (kal_uintptr)(KAL_RANDOM_PROP_HARDWARE);
inline constexpr kal_uintptr seek_current                 = (kal_uintptr)(KAL_SEEK_CURRENT);
inline constexpr kal_uintptr seek_end                     = (kal_uintptr)(KAL_SEEK_END);
inline constexpr kal_uintptr seek_set                     = (kal_uintptr)(KAL_SEEK_SET);
inline constexpr kal_uintptr shut_both                    = (kal_uintptr)(KAL_SHUT_BOTH);
inline constexpr kal_uintptr shut_read                    = (kal_uintptr)(KAL_SHUT_READ);
inline constexpr kal_uintptr shut_write                   = (kal_uintptr)(KAL_SHUT_WRITE);
inline constexpr kal_uintptr space_prop_clone_handles     = (kal_uintptr)(KAL_SPACE_PROP_CLONE_HANDLES);
inline constexpr kal_uintptr space_prop_deferred_copy     = (kal_uintptr)(KAL_SPACE_PROP_DEFERRED_COPY);
inline constexpr kal_uintptr spawn_bound_lifetime         = (kal_uintptr)(KAL_SPAWN_BOUND_LIFETIME);
inline constexpr kal_uintptr spawn_own_job                = (kal_uintptr)(KAL_SPAWN_OWN_JOB);
inline constexpr kal_uintptr stream_prop_interactive      = (kal_uintptr)(KAL_STREAM_PROP_INTERACTIVE);
inline constexpr kal_uintptr task_prop_parallel           = (kal_uintptr)(KAL_TASK_PROP_PARALLEL);
inline constexpr kal_uintptr task_prop_preemptive         = (kal_uintptr)(KAL_TASK_PROP_PREEMPTIVE);
inline constexpr kal_uintptr task_prop_thread_local       = (kal_uintptr)(KAL_TASK_PROP_THREAD_LOCAL);
inline constexpr kal_uintptr task_prop_wait_timeout       = (kal_uintptr)(KAL_TASK_PROP_WAIT_TIMEOUT);
inline constexpr kal_uintptr term_echo                    = (kal_uintptr)(KAL_TERM_ECHO);
inline constexpr kal_uintptr term_line_edit               = (kal_uintptr)(KAL_TERM_LINE_EDIT);
inline constexpr kal_uintptr term_prop_mode               = (kal_uintptr)(KAL_TERM_PROP_MODE);
inline constexpr kal_uintptr term_prop_size               = (kal_uintptr)(KAL_TERM_PROP_SIZE);
inline constexpr kal_uintptr time_prop_monotonic_suspends = (kal_uintptr)(KAL_TIME_PROP_MONOTONIC_SUSPENDS);
inline constexpr kal_uintptr time_prop_sleep_precise      = (kal_uintptr)(KAL_TIME_PROP_SLEEP_PRECISE);
inline constexpr kal_uintptr time_prop_wall_available     = (kal_uintptr)(KAL_TIME_PROP_WALL_AVAILABLE);
inline constexpr kal_uintptr version                      = (kal_uintptr)(KAL_VERSION);
inline constexpr kal_uintptr version_major                = (kal_uintptr)(KAL_VERSION_MAJOR);
inline constexpr kal_uintptr version_minor                = (kal_uintptr)(KAL_VERSION_MINOR);
inline constexpr kal_uintptr version_patch                = (kal_uintptr)(KAL_VERSION_PATCH);
}  // namespace kal::macros

// Function-like, and therefore not constants --- listed so that their absence
// above is a stated fact rather than a gap:
//   KAL_VERSION_MAKE
