// Every KAL_ macro, as a constant a module consumer can name.
//
// ⚠️⚠️ GENERATED BY tools/gen-macros.sh. Do not edit; CI regenerates this file
// and fails on a difference.
//
// A macro does not cross a module boundary. Twice now a capability word has been
// added to a header, used from a module consumer, and failed to compile there ---
// `KAL_LOCK_*' in 0.10 and `KAL_SPAWN_*' in 0.11. The interface modules give the
// well-named subset (`kal::fs::lock::exclusive'); this gives ALL of them under
// the C spelling with a `_M' suffix, so that a name in the header always exists
// here too and the two cannot drift.
module;
#include <openkal/abort.h>
#include <openkal/datagram.h>
#include <openkal/env.h>
#include <openkal/exec.h>
#include <openkal/fs.h>
#include <openkal/memory.h>
#include <openkal/net.h>
#include <openkal/process.h>
#include <openkal/random.h>
#include <openkal/space.h>
#include <openkal/stream.h>
#include <openkal/task.h>
#include <openkal/terminal.h>
#include <openkal/time.h>
#include <openkal/timeout.h>
#include <openkal/types.h>
#include <openkal/version.h>
export module openkal.macros;
export import openkal.types;

export namespace kal::macros {
inline constexpr kal_uintptr KAL_DGRAM_PROP_BROADCAST_M         = (kal_uintptr)(KAL_DGRAM_PROP_BROADCAST);
inline constexpr kal_uintptr KAL_DGRAM_PROP_IPV6_M              = (kal_uintptr)(KAL_DGRAM_PROP_IPV6);
inline constexpr kal_uintptr KAL_EXEC_PROP_AVAILABLE_M          = (kal_uintptr)(KAL_EXEC_PROP_AVAILABLE);
inline constexpr kal_uintptr KAL_EXEC_PROP_REPUBLISH_M          = (kal_uintptr)(KAL_EXEC_PROP_REPUBLISH);
inline constexpr kal_uintptr KAL_FS_LINK_DIRECTORY_M            = (kal_uintptr)(KAL_FS_LINK_DIRECTORY);
inline constexpr kal_uintptr KAL_FS_NO_RESOLVE_M                = (kal_uintptr)(KAL_FS_NO_RESOLVE);
inline constexpr kal_uintptr KAL_FS_PROP_ATOMIC_RENAME_M        = (kal_uintptr)(KAL_FS_PROP_ATOMIC_RENAME);
inline constexpr kal_uintptr KAL_FS_PROP_CAPACITY_M             = (kal_uintptr)(KAL_FS_PROP_CAPACITY);
inline constexpr kal_uintptr KAL_FS_PROP_CASE_SENSITIVE_M       = (kal_uintptr)(KAL_FS_PROP_CASE_SENSITIVE);
inline constexpr kal_uintptr KAL_FS_PROP_LINKS_M                = (kal_uintptr)(KAL_FS_PROP_LINKS);
inline constexpr kal_uintptr KAL_FS_PROP_LOCKS_M                = (kal_uintptr)(KAL_FS_PROP_LOCKS);
inline constexpr kal_uintptr KAL_FS_PROP_MAKE_LINKS_M           = (kal_uintptr)(KAL_FS_PROP_MAKE_LINKS);
inline constexpr kal_uintptr KAL_FS_PROP_MODIFIED_TIME_M        = (kal_uintptr)(KAL_FS_PROP_MODIFIED_TIME);
inline constexpr kal_uintptr KAL_IFACE_ABORT_M                  = (kal_uintptr)(KAL_IFACE_ABORT);
inline constexpr kal_uintptr KAL_IFACE_DATAGRAM_M               = (kal_uintptr)(KAL_IFACE_DATAGRAM);
inline constexpr kal_uintptr KAL_IFACE_ENV_M                    = (kal_uintptr)(KAL_IFACE_ENV);
inline constexpr kal_uintptr KAL_IFACE_EXEC_M                   = (kal_uintptr)(KAL_IFACE_EXEC);
inline constexpr kal_uintptr KAL_IFACE_FS_M                     = (kal_uintptr)(KAL_IFACE_FS);
inline constexpr kal_uintptr KAL_IFACE_MEMORY_M                 = (kal_uintptr)(KAL_IFACE_MEMORY);
inline constexpr kal_uintptr KAL_IFACE_NET_M                    = (kal_uintptr)(KAL_IFACE_NET);
inline constexpr kal_uintptr KAL_IFACE_PROCESS_M                = (kal_uintptr)(KAL_IFACE_PROCESS);
inline constexpr kal_uintptr KAL_IFACE_RANDOM_M                 = (kal_uintptr)(KAL_IFACE_RANDOM);
inline constexpr kal_uintptr KAL_IFACE_SPACE_M                  = (kal_uintptr)(KAL_IFACE_SPACE);
inline constexpr kal_uintptr KAL_IFACE_STREAM_M                 = (kal_uintptr)(KAL_IFACE_STREAM);
inline constexpr kal_uintptr KAL_IFACE_TASK_M                   = (kal_uintptr)(KAL_IFACE_TASK);
inline constexpr kal_uintptr KAL_IFACE_TERMINAL_M               = (kal_uintptr)(KAL_IFACE_TERMINAL);
inline constexpr kal_uintptr KAL_IFACE_TIME_M                   = (kal_uintptr)(KAL_IFACE_TIME);
inline constexpr kal_uintptr KAL_IFACE_TIMEOUT_M                = (kal_uintptr)(KAL_IFACE_TIMEOUT);
inline constexpr kal_uintptr KAL_INFO_ALL_M                     = (kal_uintptr)(KAL_INFO_ALL);
inline constexpr kal_uintptr KAL_INFO_IDENTITY_M                = (kal_uintptr)(KAL_INFO_IDENTITY);
inline constexpr kal_uintptr KAL_INFO_KIND_M                    = (kal_uintptr)(KAL_INFO_KIND);
inline constexpr kal_uintptr KAL_INFO_MODIFIED_M                = (kal_uintptr)(KAL_INFO_MODIFIED);
inline constexpr kal_uintptr KAL_INFO_SIZE_M                    = (kal_uintptr)(KAL_INFO_SIZE);
inline constexpr kal_uintptr KAL_INFO_WRITABLE_M                = (kal_uintptr)(KAL_INFO_WRITABLE);
inline constexpr kal_uintptr KAL_LOCK_EXCLUSIVE_M               = (kal_uintptr)(KAL_LOCK_EXCLUSIVE);
inline constexpr kal_uintptr KAL_LOCK_SHARED_M                  = (kal_uintptr)(KAL_LOCK_SHARED);
inline constexpr kal_uintptr KAL_LOCK_WAIT_M                    = (kal_uintptr)(KAL_LOCK_WAIT);
inline constexpr kal_uintptr KAL_NET_PROP_HALFCLOSE_M           = (kal_uintptr)(KAL_NET_PROP_HALFCLOSE);
inline constexpr kal_uintptr KAL_NET_PROP_IPV6_M                = (kal_uintptr)(KAL_NET_PROP_IPV6);
inline constexpr kal_uintptr KAL_OPEN_APPEND_M                  = (kal_uintptr)(KAL_OPEN_APPEND);
inline constexpr kal_uintptr KAL_OPEN_CREATE_M                  = (kal_uintptr)(KAL_OPEN_CREATE);
inline constexpr kal_uintptr KAL_OPEN_EXCLUSIVE_M               = (kal_uintptr)(KAL_OPEN_EXCLUSIVE);
inline constexpr kal_uintptr KAL_OPEN_READ_M                    = (kal_uintptr)(KAL_OPEN_READ);
inline constexpr kal_uintptr KAL_OPEN_TRUNCATE_M                = (kal_uintptr)(KAL_OPEN_TRUNCATE);
inline constexpr kal_uintptr KAL_OPEN_WRITE_M                   = (kal_uintptr)(KAL_OPEN_WRITE);
inline constexpr kal_uintptr KAL_PROCESS_PROP_BOUND_LIFETIME_M  = (kal_uintptr)(KAL_PROCESS_PROP_BOUND_LIFETIME);
inline constexpr kal_uintptr KAL_PROCESS_PROP_CHANNEL_M         = (kal_uintptr)(KAL_PROCESS_PROP_CHANNEL);
inline constexpr kal_uintptr KAL_PROCESS_PROP_EXIT_STATUS_M     = (kal_uintptr)(KAL_PROCESS_PROP_EXIT_STATUS);
inline constexpr kal_uintptr KAL_PROCESS_PROP_GRANT_DIR_M       = (kal_uintptr)(KAL_PROCESS_PROP_GRANT_DIR);
inline constexpr kal_uintptr KAL_PROCESS_PROP_OWN_JOB_M         = (kal_uintptr)(KAL_PROCESS_PROP_OWN_JOB);
inline constexpr kal_uintptr KAL_PROCESS_PROP_STREAM_PASSING_M  = (kal_uintptr)(KAL_PROCESS_PROP_STREAM_PASSING);
inline constexpr kal_uintptr KAL_PROCESS_PROP_TERMINATE_M       = (kal_uintptr)(KAL_PROCESS_PROP_TERMINATE);
inline constexpr kal_uintptr KAL_RANDOM_PROP_BLOCKING_M         = (kal_uintptr)(KAL_RANDOM_PROP_BLOCKING);
inline constexpr kal_uintptr KAL_RANDOM_PROP_HARDWARE_M         = (kal_uintptr)(KAL_RANDOM_PROP_HARDWARE);
inline constexpr kal_uintptr KAL_SEEK_CURRENT_M                 = (kal_uintptr)(KAL_SEEK_CURRENT);
inline constexpr kal_uintptr KAL_SEEK_END_M                     = (kal_uintptr)(KAL_SEEK_END);
inline constexpr kal_uintptr KAL_SEEK_SET_M                     = (kal_uintptr)(KAL_SEEK_SET);
inline constexpr kal_uintptr KAL_SHUT_BOTH_M                    = (kal_uintptr)(KAL_SHUT_BOTH);
inline constexpr kal_uintptr KAL_SHUT_READ_M                    = (kal_uintptr)(KAL_SHUT_READ);
inline constexpr kal_uintptr KAL_SHUT_WRITE_M                   = (kal_uintptr)(KAL_SHUT_WRITE);
inline constexpr kal_uintptr KAL_SPACE_PROP_CLONE_HANDLES_M     = (kal_uintptr)(KAL_SPACE_PROP_CLONE_HANDLES);
inline constexpr kal_uintptr KAL_SPACE_PROP_DEFERRED_COPY_M     = (kal_uintptr)(KAL_SPACE_PROP_DEFERRED_COPY);
inline constexpr kal_uintptr KAL_SPAWN_BOUND_LIFETIME_M         = (kal_uintptr)(KAL_SPAWN_BOUND_LIFETIME);
inline constexpr kal_uintptr KAL_SPAWN_OWN_JOB_M                = (kal_uintptr)(KAL_SPAWN_OWN_JOB);
inline constexpr kal_uintptr KAL_STREAM_PROP_INTERACTIVE_M      = (kal_uintptr)(KAL_STREAM_PROP_INTERACTIVE);
inline constexpr kal_uintptr KAL_TASK_PROP_PARALLEL_M           = (kal_uintptr)(KAL_TASK_PROP_PARALLEL);
inline constexpr kal_uintptr KAL_TASK_PROP_PREEMPTIVE_M         = (kal_uintptr)(KAL_TASK_PROP_PREEMPTIVE);
inline constexpr kal_uintptr KAL_TASK_PROP_THREAD_LOCAL_M       = (kal_uintptr)(KAL_TASK_PROP_THREAD_LOCAL);
inline constexpr kal_uintptr KAL_TASK_PROP_WAIT_TIMEOUT_M       = (kal_uintptr)(KAL_TASK_PROP_WAIT_TIMEOUT);
inline constexpr kal_uintptr KAL_TERM_ECHO_M                    = (kal_uintptr)(KAL_TERM_ECHO);
inline constexpr kal_uintptr KAL_TERM_LINE_EDIT_M               = (kal_uintptr)(KAL_TERM_LINE_EDIT);
inline constexpr kal_uintptr KAL_TERM_PROP_MODE_M               = (kal_uintptr)(KAL_TERM_PROP_MODE);
inline constexpr kal_uintptr KAL_TERM_PROP_SIZE_M               = (kal_uintptr)(KAL_TERM_PROP_SIZE);
inline constexpr kal_uintptr KAL_TIME_PROP_MONOTONIC_SUSPENDS_M = (kal_uintptr)(KAL_TIME_PROP_MONOTONIC_SUSPENDS);
inline constexpr kal_uintptr KAL_TIME_PROP_SLEEP_PRECISE_M      = (kal_uintptr)(KAL_TIME_PROP_SLEEP_PRECISE);
inline constexpr kal_uintptr KAL_TIME_PROP_WALL_AVAILABLE_M     = (kal_uintptr)(KAL_TIME_PROP_WALL_AVAILABLE);
inline constexpr kal_uintptr KAL_VERSION_M                      = (kal_uintptr)(KAL_VERSION);
inline constexpr kal_uintptr KAL_VERSION_MAJOR_M                = (kal_uintptr)(KAL_VERSION_MAJOR);
inline constexpr kal_uintptr KAL_VERSION_MINOR_M                = (kal_uintptr)(KAL_VERSION_MINOR);
inline constexpr kal_uintptr KAL_VERSION_PATCH_M                = (kal_uintptr)(KAL_VERSION_PATCH);
}  // namespace kal::macros

// Function-like, and therefore not constants --- listed so that their absence
// above is a stated fact rather than a gap:
//   KAL_VERSION_MAKE
